### ISSUE TITLE
Add JSON logging

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/single-cell-explorer#540] opened 2022-11-21 18:20 UTC
See [Data Portal logging configuration](https://github.com/chanzuckerberg/single-cell-data-portal/blob/3879427ca1358880e1b5bb09eeb1ad9ae3ef364f/backend/api_server/logger.py#L8-L38) for how to introduce JSON logging to the BE of Explorer.

**Comment by atolopko-czi** [comment] 2022-12-06 22:08
dup of #352?

**Comment by metakuni** [comment] 2023-02-06 05:01
Since this is a duplicate of 352, shall we close this issue?

**Closed** 2023-02-06 13:16 UTC
Labels: tech, P2
