### ISSUE TITLE
Add the data portal navbar to explorer

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/single-cell-explorer#383] opened 2022-08-10 15:04 UTC
Desired outcome:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16548075/183938913-e5efff40-1d02-4126-8588-4252ddc602ed.png">

Implementation considerations:
 - In an ideal world, we have a monorepo so changes to the navbar component will apply to both data portal and explorer pages. Alternatively, we could have a separate component library for the navbar that will be upstream of data portal and explorer. The latter two options are much more overhead than simply copying the navbar and its import dependency tree into explorer. Changes to nav bar styling in data portal will have to be manually mirrored in explorer.
 - The data portal navigation bar uses Next.js Links/Routers to switch between pages and determine if a page is active or not. Simply adding Next.js dependencies to explorer is not sufficient. Because none of the links in the navbar will be active when on explorer, the router logic is unnecessary (`useRouter` is used only to check if we are on a particular page for highlighting the link). 
 - The cellxgene information hamburger menu will need to be added to the navbar. The current logo and title can go.

**Comment by tihuan** [comment] 2022-09-09 16:57
Duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-explorer/411

**Closed by tihuan** 2022-09-09 16:57 UTC
